version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm i -g @angular/cli
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - ng build --prod
artifacts:
  base-directory: dist/my-app
  files:
    - '**/*'
